# Generated by Django 5.1.4 on 2025-02-20 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.IntegerField()),
                ('del_price', models.IntegerField()),
                ('des', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('quantity', models.IntegerField(default=0)),
                ('cate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
            ],
        ),
    ]
