# Generated by Django 5.1.4 on 2025-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_coupon_apply_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(blank=True, max_length=25, null=True)),
                ('ln', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('mn', models.IntegerField(default=0)),
                ('addressline1', models.CharField(blank=True, max_length=125, null=True)),
                ('addressline2', models.CharField(blank=True, max_length=125, null=True)),
                ('country', models.CharField(blank=True, max_length=125, null=True)),
                ('pincode', models.IntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
