# Generated by Django 5.1.4 on 2025-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_address_delete_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='shiping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiping_city', models.CharField(max_length=50)),
                ('shiping_charge', models.IntegerField()),
            ],
        ),
    ]
