# Generated by Django 4.2 on 2025-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
