# Generated by Django 4.2 on 2025-03-29 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_rating_user_rating_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='address',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.shiping')),
            ],
        ),
    ]
