# Generated by Django 4.2 on 2025-03-29 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_address_delivery_boy_address_status_deliveryboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='myapp.deliveryboy'),
        ),
    ]
